### ISSUE TITLE
May you provide test model?

### ISSUE THREAD

**Issue by xueliangh** [BITLIULONGEE/Triple-Adjacent-Frame-Generative-Network#3]
May you provide test model?

I also do related research and want to cite your paper for comparison
thank you!

**Comment by leandepk** [comment]
您现在还需要这个训练权重吗？原作者已经毕业了，没时间管理这个GitHub，如果你还需要权重的话可以把邮箱给我我发给您。

**Comment by xueliangh** [comment]
非常的需要!我的郵箱是:F107152157@nkust.edu.tw感謝您，想再請教一個問題，請問要執行測試的話影像是要像資料夾內那些影像使用3幀影像與gt拼接成一張嗎?感謝回覆

**Comment by leandepk** [comment]
测试是不需要的gt的，你输入连续的三帧就行了，加入gt是训练的时候








------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"蕭學良"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月7日(星期二) 中午11:27
收件人:&nbsp;"BITLIULONGEE/Triple-Adjacent-Frame-Generative-Network"<Triple-Adjacent-Frame-Generative-Network@noreply.github.com&gt;;
抄送:&nbsp;"1413458646"<1413458646@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [BITLIULONGEE/Triple-Adjacent-Frame-Generative-Network] May you provide test model? (#3)





 
非常的需要!我的郵箱是:F107152157@nkust.edu.tw感謝您，想再請教一個問題，請問要執行測試的話影像是要像資料夾內那些影像使用3幀影像與gt拼接成一張嗎?感謝回覆

**Comment by leandepk** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"蕭學良"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月7日(星期二) 中午11:27
收件人:&nbsp;"BITLIULONGEE/Triple-Adjacent-Frame-Generative-Network"<Triple-Adjacent-Frame-Generative-Network@noreply.github.com&gt;;
抄送:&nbsp;"1413458646"<1413458646@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [BITLIULONGEE/Triple-Adjacent-Frame-Generative-Network] May you provide test model? (#3)





 
非常的需要!我的郵箱是:F107152157@nkust.edu.tw感謝您，想再請教一個問題，請問要執行測試的話影像是要像資料夾內那些影像使用3幀影像與gt拼接成一張嗎?感謝回覆
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

model.tar (1.21G, 2020年05月07日 15:17 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=0a6465623273f884e2ce5a36146357195655570405065c50195c5453064e5150065c48030a55061b52565204515a5c0f05055554326a655b5b00000e1c1704443459&t=exs_ftn_download&code=4deb2ce6

**Comment by xueliangh** [comment]
@leandepk 非常感謝您，可以請問您的環境Tensorflow是什麼版本嗎?有遇到一些問題
像是模型讀取
 [*] Loading checkpoint...
model_checkpoint_path: "./checkpoints/TripleFrameDeblur\\model-3599999.index"

INFO:tensorflow:Restoring parameters from ./checkpoints/TripleFrameDeblur\model-3599999.index
I0407 17:27:07.865325 17548 saver.py:1280] Restoring parameters from ./checkpoints/TripleFrameDeblur\model-3599999.index
Traceback (most recent call last):
  File "C:\Users\Msplab\Anaconda3\envs\srn\lib\site-packages\tensorflow\python\client\session.py", line 1356, in _do_call
    return fn(*args)
  File "C:\Users\Msplab\Anaconda3\envs\srn\lib\site-packages\tensorflow\python\client\session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\Msplab\Anaconda3\envs\srn\lib\site-packages\tensorflow\python\client\session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Tensor name "gen/fd_conv1_1/W" not found in checkpoint files ./checkpoints/TripleFrameDeblur\model-3599999.index
         [[{{node save/RestoreV2}}]]

好像是變數名稱有改變?

**Comment by leandepk** [comment]
@s12121296 python是3.7的，TensorFlow是1.14的

**Comment by xueliangh** [comment]
@leandepk 目前環境版本已經設置一樣了 我剛剛試了許久，還是有一些問題... 我發現在讀權重時
model-3599999.index這個權重缺少了model.Temporal_Merge內的top4和bottom3層

而另一個model-3593999.index有top3所以我把top4改成top3但又遇到其他問題
2 root error(s) found.
  (0) Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [1,1,256,128] rhs shape= [1,1,128,64]
	 [[node save/Assign_204 (defined at /Users/Msplab/Desktop/Triple-Adjacent-Frame-Generative-Network-master/Triple-Adjacent-Frame-Generative-Network-master/test.py:59) ]]
	 [[save/RestoreV2/_472]]
  (1) Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [1,1,256,128] rhs shape= [1,1,128,64]
	 [[node save/Assign_204 (defined at /Users/Msplab/Desktop/Triple-Adjacent-Frame-Generative-Network-master/Triple-Adjacent-Frame-Generative-Network-master/test.py:59) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node save/Assign_204:
 gen/sd_merge2/top1/W (defined at \Users\Msplab\Anaconda3\envs\tttt\lib\site-packages\tensorpack\models\tflayer.py:88)

Input Source operations connected to node save/Assign_204:
 gen/sd_merge2/top1/W (defined at \Users\Msplab\Anaconda3\envs\tttt\lib\site-packages\tensorpack\models\tflayer.py:88)

出錯的部分一直都在讀取模型的地方，我想說會不會這個權重是後來訓練的，可能有修改內容導致跟Github這個專案的架構不太一樣?想詢問有沒有目前的程式專案，或是當初這個專案裡的這幾個權重，感謝幫忙
model_checkpoint_path: "model-3617249"
all_model_checkpoint_paths: "model-3593249"
all_model_checkpoint_paths: "model-3599249"
all_model_checkpoint_paths: "model-3605249"
all_model_checkpoint_paths: "model-3611249"
all_model_checkpoint_paths: "model-3617249"

**Comment by leandepk** [comment]
@s12121296 我在帮您找找吧，因为现在疫情的影响，我回不去学校，这个权重还是19年时候训练的，我也给忘了，网络的框架应该是没有改变的，我看看能不能找到最开始的那个框架给您发过去

**Comment by leandepk** [comment]
@s12121296 我已经通过另外一个邮箱把所有的东西发给您了,希望能够帮助到您

**Comment by xueliangh** [comment]
@leandepk  收到了!可以正常運行，非常感謝您的幫助，因為網上視頻去模糊能運行的很少，對我幫助很大，謝謝!

**Comment by leandepk** [comment]
@s12121296 没事，很高兴能帮助到您。

**Comment by von101** [comment]
您好，我也在做相关工作的研究，请问可以提供一份test model到我的邮箱吗？我的邮箱是von101@163.com，万分感谢。

**Comment by NTGN** [comment]
您好，目前我也在从事相关研究，并希望能引用您的论文，但上述的权重链接已失效，可以再次提供测试权重的下载链接吗？

**Comment by leandepk** [comment]
我已经把这个上传到百度网盘了，需要的请自行下载链接：https://pan.baidu.com/s/1ymEH2jJKrejUjaNENxD7Ug 
提取码：kv97
